apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vidra-operator.fullname" . }}-manager-role
  labels:
  {{- include "vidra-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrahub.operators.com
  resources:
  - infrahubresources
  - infrahubsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrahub.operators.com
  resources:
  - infrahubresources/finalizers
  - infrahubsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - infrahub.operators.com
  resources:
  - infrahubresources/status
  - infrahubsyncs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vidra-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "vidra-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "vidra-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "vidra-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'