coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 10%
    patch:
      default:
        target: 80%
        threshold: 5%
# Codecov: skip file as the event test does not run in gh actions
ignore:
  - "**/controller/watch_trigger.go"
