# permissions for end users to view infrahubresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: infrahub-operator
    app.kubernetes.io/managed-by: kustomize
  name: infrahubresource-viewer-role
rules:
- apiGroups:
  - infrahub.operators.com
  resources:
  - infrahubresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrahub.operators.com
  resources:
  - infrahubresources/status
  verbs:
  - get
