# permissions for end users to view vidraresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vidra
    app.kubernetes.io/managed-by: kustomize
  name: vidraresource-viewer-role
rules:
- apiGroups:
  - vidra.operators.com
  resources:
  - vidraresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vidra.operators.com
  resources:
  - vidraresources/status
  verbs:
  - get
