---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vidra.operators.com
  resources:
  - Vidraresources
  - infrahubsyncs
  - vidraresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vidra.operators.com
  resources:
  - Vidraresources/finalizers
  - infrahubsyncs/finalizers
  - vidraresources/finalizers
  verbs:
  - update
- apiGroups:
  - vidra.operators.com
  resources:
  - Vidraresources/status
  - infrahubsyncs/status
  - vidraresources/status
  verbs:
  - get
  - patch
  - update
