---
name: ✅ Task
description: Create a task for minor issues that isn't a feature or a bug
title: 'task: '
labels: ["type/task"]
body:
  - type: dropdown
    attributes:
      label: Component
      description: Please indicate which component(s) this task is associated with (leave blank if unknown)
      multiple: true
      options:
        - Vidra Operator
        - Vidra CLI
  - type: textarea
    attributes:
      label: Task Description
      description: A clear description of what it is you think should be done.
    validations:
      required: true
