apiVersion: infrahub.operators.com/v1alpha1
kind: VidraResource
metadata:
  name: 1834265b-8d16-4e4a-3bd9-c518b7dc1939
spec:
  manifest: '{"apiVersion": "v1", "kind": "ConfigMap", "metadata": {"name": "example", "namespace": "default"}, "data": {"key": "value"}}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'

