apiVersion: infrahub.operators.com/v1alpha1
kind: VidraResource
metadata:
  labels:
    app.kubernetes.io/name: vidra
    app.kubernetes.io/managed-by: kustomize
  name: vidraresource-sample
spec:
  manifest: '{"apiVersion": "v1", "kind": "ConfigMap", "metadata": {"name": "example", "namespace": "default"}, "data": {"key": "value"}}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
