apiVersion: infrahub.operators.com/v1alpha1
kind: InfrahubSync
metadata:
  labels:
    app.kubernetes.io/name: infrahub-operator
    app.kubernetes.io/managed-by: kustomize
  name: infrahubsync-sample
spec:
  # TODO(user): Add fields here
