apiVersion: infrahub.operators.com/v1alpha1
kind: InfrahubResource
metadata:
  labels:
    app.kubernetes.io/name: infrahub-operator
    app.kubernetes.io/managed-by: kustomize
  name: infrahubresource-sample
spec:
  # TODO(user): Add fields here
