apiVersion: infrahub.operators.com/v1alpha1
kind: InfrahubSync
metadata:
  labels:
    app.kubernetes.io/name: vidra
    app.kubernetes.io/managed-by: kustomize
  name: infrahubsync-sample
spec:
  source:
    infrahubAPIURL: "https://infrahub-server.infrahub.orb.local"
    targetBranch: "main"
    targetDate: "2025-04-09T00:00:00Z"
    artefactName: "Webserver_Manifest"
  destination:
    server: <your-kubernetes-api-server If not local>
    namespace: 'default'
    reconcileOnEvents: true
