apiVersion: infrahub.operators.com/v1alpha1
kind: InfrahubSync
metadata:
  name: sync-main
  labels:
    app.kubernetes.io/name: vidra
    app.kubernetes.io/managed-by: kustomize
spec:
  source:
    infrahubAPIURL: "https://infrahub-server.infrahub.orb.local"
    targetBranch: "main"
    # targetDate: "2025-04-09T00:00:00Z"
    artefactName: "VirtuellMaschine_Manifest"
  destination:
    # server: 'https://kubernetes.default.svc'
    namespace: 'default'
