apiVersion: infrahub.operators.com/v1alpha1
kind: InfrahubSync
metadata:
  name: sync-test-multi-x
  labels:
    app.kubernetes.io/name: vidra
    app.kubernetes.io/managed-by: kustomize
spec:
  source:
    infrahubAPIURL: "https://infrahub-server.infrahub.orb.local"
    targetBranch: "test-multi"
    # targetDate: "2025-04-09T00:00:00Z"
    artefactName: "Webserver_Manifest"
  destination:
    # server: 'https://k8s-cldop-test-0.network.garden:6443'
    namespace: 'default'
    reconcileOnEvents: true
