//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubResource) DeepCopyInto(out *InfrahubResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubResource.
func (in *InfrahubResource) DeepCopy() *InfrahubResource {
	if in == nil {
		return nil
	}
	out := new(InfrahubResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrahubResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubResourceIDs) DeepCopyInto(out *InfrahubResourceIDs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubResourceIDs.
func (in *InfrahubResourceIDs) DeepCopy() *InfrahubResourceIDs {
	if in == nil {
		return nil
	}
	out := new(InfrahubResourceIDs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubResourceList) DeepCopyInto(out *InfrahubResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrahubResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubResourceList.
func (in *InfrahubResourceList) DeepCopy() *InfrahubResourceList {
	if in == nil {
		return nil
	}
	out := new(InfrahubResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrahubResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubResourceSpec) DeepCopyInto(out *InfrahubResourceSpec) {
	*out = *in
	out.Source = in.Source
	out.Destination = in.Destination
	out.IDs = in.IDs
	in.ReconciledAt.DeepCopyInto(&out.ReconciledAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubResourceSpec.
func (in *InfrahubResourceSpec) DeepCopy() *InfrahubResourceSpec {
	if in == nil {
		return nil
	}
	out := new(InfrahubResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubResourceStatus) DeepCopyInto(out *InfrahubResourceStatus) {
	*out = *in
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	in.LastSyncTime.DeepCopyInto(&out.LastSyncTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubResourceStatus.
func (in *InfrahubResourceStatus) DeepCopy() *InfrahubResourceStatus {
	if in == nil {
		return nil
	}
	out := new(InfrahubResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubSync) DeepCopyInto(out *InfrahubSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubSync.
func (in *InfrahubSync) DeepCopy() *InfrahubSync {
	if in == nil {
		return nil
	}
	out := new(InfrahubSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrahubSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubSyncDestination) DeepCopyInto(out *InfrahubSyncDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubSyncDestination.
func (in *InfrahubSyncDestination) DeepCopy() *InfrahubSyncDestination {
	if in == nil {
		return nil
	}
	out := new(InfrahubSyncDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubSyncList) DeepCopyInto(out *InfrahubSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrahubSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubSyncList.
func (in *InfrahubSyncList) DeepCopy() *InfrahubSyncList {
	if in == nil {
		return nil
	}
	out := new(InfrahubSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrahubSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubSyncSource) DeepCopyInto(out *InfrahubSyncSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubSyncSource.
func (in *InfrahubSyncSource) DeepCopy() *InfrahubSyncSource {
	if in == nil {
		return nil
	}
	out := new(InfrahubSyncSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubSyncSpec) DeepCopyInto(out *InfrahubSyncSpec) {
	*out = *in
	out.Source = in.Source
	out.Destination = in.Destination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubSyncSpec.
func (in *InfrahubSyncSpec) DeepCopy() *InfrahubSyncSpec {
	if in == nil {
		return nil
	}
	out := new(InfrahubSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrahubSyncStatus) DeepCopyInto(out *InfrahubSyncStatus) {
	*out = *in
	in.LastSyncTime.DeepCopyInto(&out.LastSyncTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrahubSyncStatus.
func (in *InfrahubSyncStatus) DeepCopy() *InfrahubSyncStatus {
	if in == nil {
		return nil
	}
	out := new(InfrahubSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResourceStatus) DeepCopyInto(out *ManagedResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResourceStatus.
func (in *ManagedResourceStatus) DeepCopy() *ManagedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedResourceStatus)
	in.DeepCopyInto(out)
	return out
}
