apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: vidra-catalog
  namespace: operators
spec:
  displayName: Vidra Operator
  image: ghcr.io/infrahub-operator/vidra-catalog:v0.0.6
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m