name: Deploy Docusaurus to GitHub Pages

on:
  push:
      branches: [ "main" ]
      # Publish semver tags as releases
      tags: [ 'v*.*.*' ]
      paths:
          - 'docs/**'
          - '.github/workflows/docs.yaml'
          - 'Makefile'
  pull_request:
      branches: [ "main" ]
      paths:
          - 'docs/**'
          - '.github/workflows/docs.yaml'
          - 'Makefile'

permissions:
  contents: write  # allows pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Generate CRD docs
        run: make generate-crd-docs

      - name: Build website
        run: npm run build
        working-directory: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          exclude_assets: |
            index.yaml
            infrahub-operator-*.tgz
