name: CLI Tool Build and Sign

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'cli/**'
      - '.github/workflows/cli.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cli/**'
      - '.github/workflows/cli.yaml'

jobs:
  build-and-sign:
    name: Build and Sign CLI
    runs-on: ubuntu-latest

    permissions:
      contents: write      # Needed for creating GitHub releases
      id-token: write      # Required for Cosign keyless signing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build CLI tool
        working-directory: ./cli
        run: |
          go build -o vidra

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign binary with Cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob \
            --yes \
            --output-signature cli/vidra.sig \
            --output-certificate cli/vidra.cert \
            ./cli/vidra

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cli-tool-signed
          path: |
            cli/cli-tool
            cli/cli-tool.sig
            cli/cli-tool.cert


      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cli/vidra
            cli/vidra.sig
            cli/vidra.cert
