name: CLI Tool Build and Sign

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'vidra-cli/**'
      - '.github/workflows/cli.yaml'
      - 'Makefile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'vidra-cli/**'
      - '.github/workflows/cli.yaml'
      - 'Makefile'

jobs:
  build-and-sign:
    name: Build and Sign CLI
    runs-on: ubuntu-latest

    permissions:
      contents: write      # Needed for creating GitHub releases
      id-token: write      # Required for Cosign keyless signing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build CLI tool
        working-directory: ./vidra-cli
        run: |
          go build -o vidra-cli

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign binary with Cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob \
            --yes \
            --output-signature vidra-cli/vidra-cli.sig \
            --output-certificate vidra-cli/vidra-cli.cert \
            ./vidra-cli/vidra-cli

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vidra-cli/vidra-cli
            vidra-cli/vidra-cli.sig
            vidra-cli/vidra-cli.cert
