name: Operator CI
on:
  push:
      branches: [ "main" ]
      tags: [ 'v*.*.*' ]
      paths:
          - 'cmd/**'
          - 'go.*'
          - 'api/**'
          - 'internal/**'
          - 'config/**'
          - 'hack/**'
          - 'test/**'
          - 'Dockerfile'
          - 'chart/**'
          - 'bundle.Dockerfile'
          - '.dockerignore'
          - 'Makefile'
          - '.github/workflows/main.yaml'
  pull_request:
      branches: [ "main" ]
      paths:
          - 'cmd/**'
          - 'go.*'
          - 'api/**'
          - 'internal/**'
          - 'config/**'
          - 'hack/**'
          - 'test/**'
          - 'Dockerfile'
          - 'chart/**'
          - 'bundle.Dockerfile'
          - '.dockerignore'
          - 'Makefile'
          - '.github/workflows/main.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  OPERATOR_SDK_VERSION: v1.39.2
  OS: linux
  TARGETARCH: amd64
  GO111MODULE: "on"
  GOCACHE: ${{ github.workspace }}/.cache/go-build
  GOPATH: ${{ github.workspace }}/.cache/go
  CGO_ENABLED: "0"
  ENVTEST_K8S_VERSION: "1.31.0"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      packages: read
      id-token: write
    container: golang:1.24
    continue-on-error: true
    env:
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            .cache/go
            .cache/go-build
          key: ${{ runner.os }}-go-${{ github.ref_name }}
      - run: go version
      - run: make fmt
      - run: make vet
      - run: make lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read
      packages: read
      id-token: write
    container: golang:1.24
    env:
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            .cache/go
            .cache/go-build
          key: ${{ runner.os }}-go-${{ github.ref_name }}
      - run: go version
      - run: make test 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
 
  build-push:
      name: Build and Push Operator Image
      if: startsWith(github.ref, 'refs/tags/v')
      needs: unit-test
      runs-on: ubuntu-latest
      permissions:
        contents: write
        packages: write
        id-token: write
      steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-qemu-action@v2
          with:
            platforms: amd64
        - uses: docker/setup-buildx-action@v2
        - name: Log into registry ${{ env.REGISTRY }}
          uses: docker/login-action@v2
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Extract Docker metadata
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        - name: Build and push Docker image
          id: build-and-push
          uses: docker/build-push-action@v4
          with:
            file: "Dockerfile"
            context: .
            platforms: linux/amd64
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
        - name: Install operator-sdk
          run: |
              curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk_${OS}_${TARGETARCH} \
              && chmod +x operator-sdk_${OS}_${TARGETARCH} \
              && mv operator-sdk_${OS}_${TARGETARCH} /usr/local/bin/operator-sdk \
              && echo $(operator-sdk version)
        - name: Create Bundle and Catalog and push to registry
          run: |
              make bundle
              make bundle-build bundle-push
              make catalog-build catalog-push
        - name: Sign the vidra-bundle and vidra-catalog images
          env:
            COSIGN_EXPERIMENTAL: "true"
          run: |
            VERSION=${GITHUB_REF#refs/tags/v}
            COSIGN_VERSION="v2.2.3"
            curl -LO https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64
            chmod +x cosign-linux-amd64
            mv cosign-linux-amd64 /usr/local/bin/cosign
            cosign version
            cosign sign ghcr.io/${{ github.repository }}/vidra-bundle:v${VERSION} --yes
            cosign sign ghcr.io/${{ github.repository }}/vidra-catalog:v${VERSION} --yes
          # Sign the resulting Docker image digest except on PRs.
          # This will only write to the public Rekor transparency log when the Docker
          # repository is public to avoid leaking data.  If you would like to publish
          # transparency data even for private images, pass --force to cosign below.
          # https://github.com/sigstore/cosign
        - name: Sign the published Docker image
          if: ${{ github.event_name != 'pull_request' }}
          env:
            COSIGN_EXPERIMENTAL: "true"
            # This step uses the identity token to provision an ephemeral certificate
            # against the sigstore community Fulcio instance.
          run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}

  helm-chart:
    name: Push Helm Chart
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Extract tag version (e.g. v0.0.2 -> 0.0.2)
        shell: bash
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: helmify
        run: make helm

      - name: Package Helm chart
        run: |
          mkdir -p .deploy
          helm package charts/vidra-operator --destination .deploy

      - name: Create Helm repo index
        run: |
          helm repo index .deploy --url https://github.com/infrahub-operator/vidra/releases/download/${GITHUB_REF#refs/tags/v}

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .deploy/vidra-operator-${{ env.TAG_VERSION }}.tgz
            .deploy/index.yaml

      - name: Create Helm repo index
        run: |
          helm repo index .deploy --url https://infrahub-operator.github.io/vidra

      - name: Upload to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .deploy
          publish_branch: gh-pages
          keep_files: true  # Keeps existing files like older chart versions
      
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: vidra-operator
          repository: ${{ github.repository }}/helm-charts
          tag: ${{ env.TAG_VERSION }}
          path: charts/vidra-operator
          registry: ghcr.io
          registry_username: ${{ github.repository_owner }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign the Helm chart OCI artifact
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          echo "ghcr.io/${{ github.repository }}/helm-charts/vidra-operator:${{ env.TAG_VERSION }}" \
          | xargs -I {} cosign sign {} --yes


  add-install-yamls-to-release:
    name: Add Install YAMLs to Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in install/catalogsource.yaml and install/subscription.yaml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s|^\(\s*image:\s*ghcr.io/infrahub-operator/vidra-catalog:\).*|\1v$VERSION|" install/catalogsource.yaml
          sed -i "s|^\(\s*startingCSV:\s*\).*|\1vidra-operator.v$VERSION|" install/subscription.yaml

      - name: Upload install YAMLs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            install/catalogsource.yaml
            install/subscription.yaml
